version: '5'


services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydatabase
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
