# Generated by Django 5.0.4 on 2024-05-06 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haypan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='comuna',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='haypan.comuna'),
        ),
    ]
