# Generated by Django 5.0.4 on 2024-05-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haypan', '0003_alter_usuario_comuna'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuario',
            name='unique_username_for_user_type',
        ),
    ]
