# Generated by Django 5.0.6 on 2024-06-05 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haypan', '0006_detallereserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='horaInicio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
